openapi: '3.0.2'
info:
  title: Auction Service
  description: This is a server that provides support for an auctioning system.
  version: '1.0'

servers:
  - url: localhost:8080
    description: Main server
    
paths:
  /auctions:
    get:
      description: Obtain information about the auctions from the database.
      responses:
        '200':
          description: Successful pull of auctions information.
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Auctions'
        '500':
          description: Internal server error.              
    post:
      description: Creates a new Auction in the database.
      requestBody:
        required: true
        content: 
          application/json:
            schema:
                type: object
                $ref: '#/components/schemas/Auction'
      responses:
        '200':
          description: Successfully created a new auction.
        '500':
          description: Internal server error.
  /auctions/:id:
    delete:
      description: Delete a specific auction from the database.
      parameters:
        - in: path
          name: id
          description: The ID of the auction
          required: true
          schema:
            type: integer
            example: 10
      responses:
        '200':
          description: Successfully deleted the auction.
        '500':
          description: Internal server error. 
        '404':
          description: Auction not found in the database.      
components:
  schemas:
    Auctions:
      description: Array of auction information.
      type: array
      items:
        $ref: '#/components/schemas/Auction'

    Auction:
      description: Model containing auction information. 
      properties:
        auctionID:
          type: integer
          example: 4

        assetIDs:
          type: array
          items:
            properties:
              auctionID:
                type: integer
                example: 5
        sellerID:
          type: integer
          example: 4
        charge:
          type: number
          example: 19.1231
        StartingTime:
          type: object
          example: 13:13:13
        EndingTimeStart:
          type: object
          example: 13:13:13
        EndingTimeEnd:
          type: object
          example: 13:13:13
        Type:
          type: string
          example: "AscendingClock"



                      


                    
